global using System;
global using System.Resources;
global using DotNext.Resources;
global using System.Diagnostics;
global using BuildingBlocks.Logging;
global using BuildingBlocks.Constants;
global using BuildingBlocks.Resources;
global using Microsoft.AspNetCore.Http;
global using BuildingBlocks.Enums.Logging;
global using Microsoft.Extensions.Logging;
global using Microsoft.AspNetCore.Builder;
global using System.Runtime.CompilerServices;
global using Microsoft.Extensions.Configuration;
global using System.ComponentModel.DataAnnotations;
global using System.Net.Mime;
global using BuildingBlocks.Patterns.Result;
global using ScGen.Lib.Contracts.BaseContracts;
global using ScGen.Lib.Enums;

